name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Branche que vous utilisez pour le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 35.180.138.235
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Stop and remove the existing container if it exists
            docker stop fastapi_template || true
            docker rm fastapi_template || true

            # Navigate to the application directory
            cd /home/ec2-user/fastapi_template

            git pull origin main

            # Build the Docker image
            docker build -t fastapi_template:latest .

            # Run the Docker container
            docker run -d --name fastapi_template -p 8000:8000 fastapi_template:latest